services:
  app:
    container_name: vue-recap
    build:
      dockerfile: Dockerfile
      target: dev-node
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    command: sh -c "npm install && npm run dev"